### ISSUE TITLE
Different Backbone

### ISSUE THREAD

**Issue by tomanick** [Meowuu7/AutoGPart#3]
Thanks for your sharing.
If I want to use a different backbone such as PVCNN, does AutoGPart support it?

**Comment by Meowuu7** [comment]
Hi,

Thanks for your attention.
I'm afraid that you need to write the backbone model you would like to use and set up the backbone in the main model's file such as `model/motion_segmodel_cls_sea_v2.py` like what we do `self.conv_uniunet = PrimitiveNet(args)` since only `DGCNN` and `PointNet++` are supported currently.
